http:
  port: 8000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: "/ip"
  catalog:
    host: localhost
    paths: "/booksMongodb/*"
  account:
    host: localhost
    paths: "/users/*"
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  catalogService:
    url: "http://localhost:3002/"
  accountService:
    url: "http://localhost:3003/"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  catalogPipe:
    apiEndpoints:
      - catalog
    policies:
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: catalogService
              changeOrigin: true
  accountPipe:
    apiEndpoints:
      - account
    policies:
      - proxy:
          - action:
              serviceEndpoint: accountService
              changeOrigin: true
